let data = [
  {
    section: "all",
    day: "saturday",
    time: "من 8:30 إلى 10:00",
    sub: "مقدمة في البرمجة",
    place: "مدرج تجارة",
  },
  {
    section: "all",
    day: "saturday",
    time: "من 10:00 إلى 11:30",
    sub: "أساسيات نظم المعلومات",
    place: "مدرج تجارة",
  },
  {
    section: "all",
    day: "saturday",
    time: "من 11:30 إلى 1:00",
    sub: "أساسيات الشبكات",
    place: "مدرج تجارة",
  },
  {
    section: "all",
    day: "saturday",
    time: "من 1:00 إلى 2:30",
    sub: "رياضيات 2",
    place: "مدرج تجارة",
  },
  {
    section: "all",
    day: "saturday",
    time: "من 2:30 إلى 4:00",
    sub: "فيزياء 2",
    place: "مدرج تجارة",
  },
  {
    section: 13,
    day: "sunday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي شبكات",
    place: "قاعة 1",
  },
  {
    section: 14,
    day: "sunday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي شبكات",
    place: "قاعة 1",
  },
  {
    section: 15,
    day: "sunday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي شبكات",
    place: "قاعة 1",
  },
  {
    section: 16,
    day: "sunday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي شبكات",
    place: "قاعة 2",
  },
  {
    section: 17,
    day: "sunday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي شبكات",
    place: "قاعة 2",
  },
  {
    section: 18,
    day: "sunday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي شبكات",
    place: "قاعة 2",
  },
  {
    section: 19,
    day: "sunday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي شبكات",
    place: "قاعة 3",
  },
  {
    section: 20,
    day: "sunday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي شبكات",
    place: "قاعة 3",
  },
  {
    section: 21,
    day: "sunday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي شبكات",
    place: "قاعة 1",
  },
  {
    section: 22,
    day: "sunday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي شبكات",
    place: "قاعة 1",
  },
  {
    section: 23,
    day: "sunday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي شبكات",
    place: "قاعة 1",
  },
  {
    section: 24,
    day: "sunday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي شبكات",
    place: "قاعة 2",
  },
  {
    section: 25,
    day: "sunday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي شبكات",
    place: "قاعة 2",
  },
  {
    section: 26,
    day: "sunday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي شبكات",
    place: "قاعة 2",
  },
  {
    section: 27,
    day: "sunday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي شبكات",
    place: "قاعة 3",
  },
  {
    section: 28,
    day: "sunday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي شبكات",
    place: "قاعة 3",
  },
  {
    section: 1,
    day: "sunday",
    time: "من 11:30 إلى  1:00",
    sub: "التصميم المنطقي",
    place: "مدرج 1",
  },
  {
    section: 2,
    day: "sunday",
    time: "من 11:30 إلى  1:00",
    sub: "التصميم المنطقي",
    place: "مدرج 1",
  },
  {
    section: 3,
    day: "sunday",
    time: "من 11:30 إلى  1:00",
    sub: "التصميم المنطقي",
    place: "مدرج 1",
  },
  {
    section: 4,
    day: "sunday",
    time: "من 11:30 إلى  1:00",
    sub: "التصميم المنطقي",
    place: "مدرج 1",
  },
  {
    section: 5,
    day: "sunday",
    time: "من 11:30 إلى  1:00",
    sub: "التصميم المنطقي",
    place: "مدرج 1",
  },
  {
    section: 6,
    day: "sunday",
    time: "من 11:30 إلى  1:00",
    sub: "التصميم المنطقي",
    place: "مدرج 1",
  },
  {
    section: 7,
    day: "sunday",
    time: "من 11:30 إلى  1:00",
    sub: "التصميم المنطقي",
    place: "مدرج 1",
  },
  {
    section: 8,
    day: "sunday",
    time: "من 11:30 إلى  1:00",
    sub: "التصميم المنطقي",
    place: "مدرج 1",
  },
  {
    section: 9,
    day: "sunday",
    time: "من 11:30 إلى  1:00",
    sub: "التصميم المنطقي",
    place: "مدرج 1",
  },
  {
    section: 10,
    day: "sunday",
    time: "من 11:30 إلى  1:00",
    sub: "التصميم المنطقي",
    place: "مدرج 1",
  },
  {
    section: 11,
    day: "sunday",
    time: "من 11:30 إلى  1:00",
    sub: "التصميم المنطقي",
    place: "مدرج 1",
  },
  {
    section: 12,
    day: "sunday",
    time: "من 11:30 إلى  1:00",
    sub: "التصميم المنطقي",
    place: "مدرج 1",
  },
  {
    section: 13,
    day: "sunday",
    time: "من 11:30 إلى  1:00",
    sub: "التصميم المنطقي",
    place: "مدرج 1",
  },
  {
    section: 14,
    day: "sunday",
    time: "من 11:30 إلى  1:00",
    sub: "التصميم المنطقي",
    place: "مدرج 1",
  },
  {
    section: 15,
    day: "sunday",
    time: "من 1:00 إلى  2:30",
    sub: "التصميم المنطقي",
    place: "مدرج 1",
  },
  {
    section: 16,
    day: "sunday",
    time: "من 1:00 إلى  2:30",
    sub: "التصميم المنطقي",
    place: "مدرج 1",
  },
  {
    section: 17,
    day: "sunday",
    time: "من 1:00 إلى  2:30",
    sub: "التصميم المنطقي",
    place: "مدرج 1",
  },
  {
    section: 18,
    day: "sunday",
    time: "من 1:00 إلى  2:30",
    sub: "التصميم المنطقي",
    place: "مدرج 1",
  },
  {
    section: 19,
    day: "sunday",
    time: "من 1:00 إلى  2:30",
    sub: "التصميم المنطقي",
    place: "مدرج 1",
  },
  {
    section: 20,
    day: "sunday",
    time: "من 1:00 إلى  2:30",
    sub: "التصميم المنطقي",
    place: "مدرج 1",
  },
  {
    section: 21,
    day: "sunday",
    time: "من 1:00 إلى  2:30",
    sub: "التصميم المنطقي",
    place: "مدرج 1",
  },
  {
    section: 22,
    day: "sunday",
    time: "من 1:00 إلى  2:30",
    sub: "التصميم المنطقي",
    place: "مدرج 1",
  },
  {
    section: 23,
    day: "sunday",
    time: "من 1:00 إلى  2:30",
    sub: "التصميم المنطقي",
    place: "مدرج 1",
  },
  {
    section: 24,
    day: "sunday",
    time: "من 1:00 إلى  2:30",
    sub: "التصميم المنطقي",
    place: "مدرج 1",
  },
  {
    section: 25,
    day: "sunday",
    time: "من 1:00 إلى  2:30",
    sub: "التصميم المنطقي",
    place: "مدرج 1",
  },
  {
    section: 26,
    day: "sunday",
    time: "من 1:00 إلى  2:30",
    sub: "التصميم المنطقي",
    place: "مدرج 1",
  },
  {
    section: 27,
    day: "sunday",
    time: "من 1:00 إلى  2:30",
    sub: "التصميم المنطقي",
    place: "مدرج 1",
  },
  {
    section: 28,
    day: "sunday",
    time: "من 1:00 إلى  2:30",
    sub: "التصميم المنطقي",
    place: "مدرج 1",
  },
  {
    section: "all",
    day: "sunday",
    time: "من 2:30 إلى 4:00",
    sub: "قضايا مجتمعيه",
    place: "مدرج 1",
  },
  {
    section: 19,
    day: "monday",
    time: "من 8:00 إلى 10:00",
    sub: "فيزياء",
    place: "الجامعة القديمة",
  },
  {
    section: 20,
    day: "monday",
    time: "من 8:00 إلى 10:00",
    sub: "فيزياء",
    place: "الجامعة القديمة",
  },
  {
    section: 21,
    day: "monday",
    time: "من 8:00 إلى 10:00",
    sub: "فيزياء",
    place: "الجامعة القديمة",
  },
  {
    section: 22,
    day: "monday",
    time: "من 10:00 إلى 12:00",
    sub: "فيزياء",
    place: "الجامعة القديمة",
  },
  {
    section: 23,
    day: "monday",
    time: "من 10:00 إلى 12:00",
    sub: "فيزياء",
    place: "الجامعة القديمة",
  },
  {
    section: 24,
    day: "monday",
    time: "من 10:00 إلى 12:00",
    sub: "فيزياء",
    place: "الجامعة القديمة",
  },
  {
    section: 25,
    day: "monday",
    time: "من 12:00 إلى 2:00",
    sub: "فيزياء",
    place: "الجامعة القديمة",
  },
  {
    section: 26,
    day: "monday",
    time: "من 12:00 إلى 2:00",
    sub: "فيزياء",
    place: "الجامعة القديمة",
  },
  {
    section: 27,
    day: "monday",
    time: "من 12:00 إلى 2:00",
    sub: "فيزياء",
    place: "الجامعة القديمة",
  },
  {
    section: 28,
    day: "monday",
    time: "من 2:00 إلى 4:00",
    sub: "فيزياء",
    place: "الجامعة القديمة",
  },
  {
    section: 29,
    day: "monday",
    time: "من 2:00 إلى 4:00",
    sub: "فيزياء",
    place: "الجامعة القديمة",
  },
  {
    section: 30,
    day: "monday",
    time: "من 2:00 إلى 4:00",
    sub: "فيزياء",
    place: "الجامعة القديمة",
  },
  {
    section: 31,
    day: "monday",
    time: "من 4:00 إلى 6:00",
    sub: "فيزياء",
    place: "الجامعة القديمة",
  },
  {
    section: 32,
    day: "monday",
    time: "من 4:00 إلى 6:00",
    sub: "فيزياء",
    place: "الجامعة القديمة",
  },
  {
    section: 33,
    day: "monday",
    time: "من 4:00 إلى 6:00",
    sub: "فيزياء",
    place: "الجامعة القديمة",
  },
  {
    section: 34,
    day: "monday",
    time: "من 6:00 إلى 8:00",
    sub: "فيزياء",
    place: "الجامعة القديمة",
  },
  {
    section: 35,
    day: "monday",
    time: "من 6:00 إلى 8:00",
    sub: "فيزياء",
    place: "الجامعة القديمة",
  },
  {
    section: 36,
    day: "monday",
    time: "من 6:00 إلى 8:00",
    sub: "فيزياء",
    place: "الجامعة القديمة",
  },
  {
    section: 1,
    day: "monday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي شبكات",
    place: "قاعة 1",
  },
  {
    section: 2,
    day: "monday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي شبكات",
    place: "قاعة 1",
  },
  {
    section: 3,
    day: "monday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي شبكات",
    place: "قاعة 1",
  },
  {
    section: 4,
    day: "monday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي شبكات",
    place: "قاعة 2",
  },
  {
    section: 5,
    day: "monday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي شبكات",
    place: "قاعة 2",
  },
  {
    section: 6,
    day: "monday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي شبكات",
    place: "قاعة 2",
  },
  {
    section: 7,
    day: "monday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي شبكات",
    place: "قاعة 1",
  },
  {
    section: 8,
    day: "monday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي شبكات",
    place: "قاعة 1",
  },
  {
    section: 9,
    day: "monday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي شبكات",
    place: "قاعة 1",
  },
  {
    section: 10,
    day: "monday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي شبكات",
    place: "قاعة 2",
  },
  {
    section: 11,
    day: "monday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي شبكات",
    place: "قاعة 2",
  },
  {
    section: 12,
    day: "monday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي شبكات",
    place: "قاعة 2",
  },
  {
    section: 1,
    day: "monday",
    time: "من 11:30 إلى 1:00",
    sub: "عملي برمجة",
    place: "معمل 6",
  },
  {
    section: 2,
    day: "monday",
    time: "من 11:30 إلى 1:00",
    sub: "عملي برمجة",
    place: "معمل 7",
  },
  {
    section: 3,
    day: "monday",
    time: "من 11:30 إلى 1:00",
    sub: "عملي برمجة",
    place: "معمل 8",
  },
  {
    section: 4,
    day: "monday",
    time: "من 11:30 إلى 1:00",
    sub: "عملي برمجة",
    place: "معمل 9",
  },
  {
    section: 5,
    day: "monday",
    time: "من 11:30 إلى 1:00",
    sub: "عملي برمجة",
    place: "معمل 10",
  },
  {
    section: 6,
    day: "monday",
    time: "من 11:30 إلى 1:00",
    sub: "عملي برمجة",
    place: "معمل 11",
  },
  {
    section: 7,
    day: "monday",
    time: "من 2:30 إلى 4:00",
    sub: "عملي برمجة",
    place: "معمل 11",
  },
  {
    section: 7,
    day: "tuseday",
    time: "من 9:30 إلى 10:30",
    sub: "عملي تصميم منطقي",
    place: "كلية هندسة قسم مدني الدور الثاني علوى فصل 304",
  },
  {
    section: 8,
    day: "tuseday",
    time: "من 9:30 إلى 10:30",
    sub: "عملي تصميم منطقي",
    place: "كلية هندسة قسم مدني الدور الثاني علوى فصل 304",
  },
  {
    section: 13,
    day: "tuseday",
    time: "من 10:30 إلى 11:30",
    sub: "عملي تصميم منطقي",
    place: "كلية هندسة قسم مدني الدور الثاني علوى فصل 304",
  },
  {
    section: 14,
    day: "tuseday",
    time: "من 10:30 إلى 11:30",
    sub: "عملي تصميم منطقي",
    place: "كلية هندسة قسم مدني الدور الثاني علوى فصل 304",
  },
  {
    section: 1,
    day: "tuseday",
    time: "من 11:30 إلى 12:30",
    sub: "عملي تصميم منطقي",
    place: "كلية هندسة قسم مدني الدور الثاني علوى فصل 304",
  },
  {
    section: 2,
    day: "tuseday",
    time: "من 11:30 إلى 12:30",
    sub: "عملي تصميم منطقي",
    place: "كلية هندسة قسم مدني الدور الثاني علوى فصل 304",
  },
  {
    section: 9,
    day: "tuseday",
    time: "من 9:30 إلى 10:30",
    sub: "عملي تصميم منطقي",
    place: "كلية هندسة قسم مدني الدور الثاني علوى فصل 305",
  },
  {
    section: 10,
    day: "tuseday",
    time: "من 9:30 إلى 10:30",
    sub: "عملي تصميم منطقي",
    place: "كلية هندسة قسم مدني الدور الثاني علوى فصل 305",
  },
  {
    section: 15,
    day: "tuseday",
    time: "من 10:30 إلى 11:30",
    sub: "عملي تصميم منطقي",
    place: "كلية هندسة قسم مدني الدور الثاني علوى فصل 305",
  },
  {
    section: 16,
    day: "tuseday",
    time: "من 10:30 إلى 11:30",
    sub: "عملي تصميم منطقي",
    place: "كلية هندسة قسم مدني الدور الثاني علوى فصل 305",
  },
  {
    section: 3,
    day: "tuseday",
    time: "من 11:30 إلى 12:30",
    sub: "عملي تصميم منطقي",
    place: "كلية هندسة قسم مدني الدور الثاني علوى فصل 305",
  },
  {
    section: 4,
    day: "tuseday",
    time: "من 11:30 إلى 12:30",
    sub: "عملي تصميم منطقي",
    place: "كلية هندسة قسم مدني الدور الثاني علوى فصل 305",
  },
  {
    section: 11,
    day: "tuseday",
    time: "من 9:30 إلى 10:30",
    sub: "عملي تصميم منطقي",
    place: "كلية هندسة قسم مدني الدور الثاني علوى فصل 307",
  },
  {
    section: 12,
    day: "tuseday",
    time: "من 9:30 إلى 10:30",
    sub: "عملي تصميم منطقي",
    place: "كلية هندسة قسم مدني الدور الثاني علوى فصل 307",
  },
  {
    section: 17,
    day: "tuseday",
    time: "من 10:30 إلى 11:30",
    sub: "عملي تصميم منطقي",
    place: "كلية هندسة قسم مدني الدور الثاني علوى فصل 307",
  },
  {
    section: 18,
    day: "tuseday",
    time: "من 10:30 إلى 11:30",
    sub: "عملي تصميم منطقي",
    place: "كلية هندسة قسم مدني الدور الثاني علوى فصل 307",
  },
  {
    section: 5,
    day: "tuseday",
    time: "من 11:30 إلى 12:30",
    sub: "عملي تصميم منطقي",
    place: "كلية هندسة قسم مدني الدور الثاني علوى فصل 307",
  },
  {
    section: 6,
    day: "tuseday",
    time: "من 11:30 إلى 12:30",
    sub: "عملي تصميم منطقي",
    place: "كلية هندسة قسم مدني الدور الثاني علوى فصل 307",
  },
  {
    section: 8,
    day: "tuseday",
    time: "من 1:00 إلى 2:30",
    sub: "عملي برمجة",
    place: "معامل من 6 - 13",
  },
  {
    section: 9,
    day: "tuseday",
    time: "من 1:00 إلى 2:30",
    sub: "عملي برمجة",
    place: "معامل من 6 - 13",
  },
  {
    section: 10,
    day: "tuseday",
    time: "من 1:00 إلى 2:30",
    sub: "عملي برمجة",
    place: "معامل من 6 - 13",
  },
  {
    section: 11,
    day: "tuseday",
    time: "من 1:00 إلى 2:30",
    sub: "عملي برمجة",
    place: "معامل من 6 - 13",
  },
  {
    section: 12,
    day: "tuseday",
    time: "من 1:00 إلى 2:30",
    sub: "عملي برمجة",
    place: "معامل من 6 - 13",
  },
  {
    section: 13,
    day: "tuseday",
    time: "من 1:00 إلى 2:30",
    sub: "عملي برمجة",
    place: "معامل من 6 - 13",
  },
  {
    section: 14,
    day: "tuseday",
    time: "من 1:00 إلى 2:30",
    sub: "عملي برمجة",
    place: "معامل من 6 - 13",
  },
  {
    section: 15,
    day: "tuseday",
    time: "من 2:30 إلى 4:00",
    sub: "عملي برمجة",
    place: "معامل من 6 - 13",
  },
  {
    section: 16,
    day: "tuseday",
    time: "من 2:30 إلى 4:00",
    sub: "عملي برمجة",
    place: "معامل من 6 - 13",
  },
  {
    section: 17,
    day: "tuseday",
    time: "من 2:30 إلى 4:00",
    sub: "عملي برمجة",
    place: "معامل من 6 - 13",
  },
  {
    section: 18,
    day: "tuseday",
    time: "من 2:30 إلى 4:00",
    sub: "عملي برمجة",
    place: "معامل من 6 - 13",
  },
  {
    section: 19,
    day: "tuseday",
    time: "من 2:30 إلى 4:00",
    sub: "عملي برمجة",
    place: "معامل من 6 - 13",
  },
  {
    section: 20,
    day: "tuseday",
    time: "من 2:30 إلى 4:00",
    sub: "عملي برمجة",
    place: "معامل من 6 - 13",
  },
  {
    section: 21,
    day: "tuseday",
    time: "من 2:30 إلى 4:00",
    sub: "عملي برمجة",
    place: "معامل من 6 - 13",
  },
  {
    section: 37,
    day: "tuseday",
    time: "من 8:00 إلى 10:00",
    sub: "فيزياء",
    place: "الجامعة القديمة",
  },
  {
    section: 38,
    day: "tuseday",
    time: "من 8:00 إلى 10:00",
    sub: "فيزياء",
    place: "الجامعة القديمة",
  },
  {
    section: 39,
    day: "tuseday",
    time: "من 8:00 إلى 10:00",
    sub: "فيزياء",
    place: "الجامعة القديمة",
  },
  {
    section: 40,
    day: "tuseday",
    time: "من 10:00 إلى 12:00",
    sub: "فيزياء",
    place: "الجامعة القديمة",
  },
  {
    section: 1,
    day: "wednesday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي نظم",
    place: "معامل من 6 - 13",
  },
  {
    section: 2,
    day: "wednesday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي نظم",
    place: "معامل من 6 - 13",
  },
  {
    section: 3,
    day: "wednesday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي نظم",
    place: "معامل من 6 - 13",
  },
  {
    section: 4,
    day: "wednesday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي نظم",
    place: "معامل من 6 - 13",
  },
  {
    section: 5,
    day: "wednesday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي نظم",
    place: "معامل من 6 - 13",
  },
  {
    section: 6,
    day: "wednesday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي نظم",
    place: "معامل من 6 - 13",
  },
  {
    section: 7,
    day: "wednesday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي نظم",
    place: "معامل من 6 - 13",
  },
  {
    section: 8,
    day: "wednesday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي نظم",
    place: "معامل من 6 - 13",
  },
  {
    section: 9,
    day: "wednesday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي نظم",
    place: "معامل من 6 - 13",
  },
  {
    section: 10,
    day: "wednesday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي نظم",
    place: "معامل من 6 - 13",
  },
  {
    section: 11,
    day: "wednesday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي نظم",
    place: "معامل من 6 - 13",
  },
  {
    section: 12,
    day: "wednesday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي نظم",
    place: "معامل من 6 - 13",
  },
  {
    section: 13,
    day: "wednesday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي نظم",
    place: "معامل من 6 - 13",
  },
  {
    section: 14,
    day: "wednesday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي نظم",
    place: "معامل من 6 - 13",
  },
  {
    section: 15,
    day: "wednesday",
    time: "من 11:30 إلى 1:00",
    sub: "عملي نظم",
    place: "معامل من 6 - 13",
  },
  {
    section: 16,
    day: "wednesday",
    time: "من 11:30 إلى 1:00",
    sub: "عملي نظم",
    place: "معامل من 6 - 13",
  },
  {
    section: 17,
    day: "wednesday",
    time: "من 11:30 إلى 1:00",
    sub: "عملي نظم",
    place: "معامل من 6 - 13",
  },
  {
    section: 18,
    day: "wednesday",
    time: "من 11:30 إلى 1:00",
    sub: "عملي نظم",
    place: "معامل من 6 - 13",
  },
  {
    section: 19,
    day: "wednesday",
    time: "من 11:30 إلى 1:00",
    sub: "عملي نظم",
    place: "معامل من 6 - 13",
  },
  {
    section: 20,
    day: "wednesday",
    time: "من 11:30 إلى 1:00",
    sub: "عملي نظم",
    place: "معامل من 6 - 13",
  },
  {
    section: 21,
    day: "wednesday",
    time: "من 11:30 إلى 1:00",
    sub: "عملي نظم",
    place: "معامل من 6 - 13",
  },
  {
    section: 22,
    day: "wednesday",
    time: "من 1:00 إلى 2:30",
    sub: "عملي نظم",
    place: "معامل من 6 - 13",
  },
  {
    section: 23,
    day: "wednesday",
    time: "من 1:00 إلى 2:30",
    sub: "عملي نظم",
    place: "معامل من 6 - 13",
  },
  {
    section: 24,
    day: "wednesday",
    time: "من 1:00 إلى 2:30",
    sub: "عملي نظم",
    place: "معامل من 6 - 13",
  },
  {
    section: 25,
    day: "wednesday",
    time: "من 1:00 إلى 2:30",
    sub: "عملي نظم",
    place: "معامل من 6 - 13",
  },
  {
    section: 26,
    day: "wednesday",
    time: "من 1:00 إلى 2:30",
    sub: "عملي نظم",
    place: "معامل من 6 - 13",
  },
  {
    section: 27,
    day: "wednesday",
    time: "من 1:00 إلى 2:30",
    sub: "عملي نظم",
    place: "معامل من 6 - 13",
  },
  {
    section: 28,
    day: "wednesday",
    time: "من 1:00 إلى 2:30",
    sub: "عملي نظم",
    place: "معامل من 6 - 13",
  },
  {
    section: 22,
    day: "wednesday",
    time: "من 2:30 إلى 4:00",
    sub: "عملي برمجة",
    place: "معامل من 6 - 13",
  },
  {
    section: 23,
    day: "wednesday",
    time: "من 2:30 إلى 4:00",
    sub: "عملي برمجة",
    place: "معامل من 6 - 13",
  },
  {
    section: 24,
    day: "wednesday",
    time: "من 2:30 إلى 4:00",
    sub: "عملي برمجة",
    place: "معامل من 6 - 13",
  },
  {
    section: 25,
    day: "wednesday",
    time: "من 2:30 إلى 4:00",
    sub: "عملي برمجة",
    place: "معامل من 6 - 13",
  },
  {
    section: 26,
    day: "wednesday",
    time: "من 2:30 إلى 4:00",
    sub: "عملي برمجة",
    place: "معامل من 6 - 13",
  },
  {
    section: 27,
    day: "wednesday",
    time: "من 2:30 إلى 4:00",
    sub: "عملي برمجة",
    place: "معامل من 6 - 13",
  },
  {
    section: 28,
    day: "wednesday",
    time: "من 2:30 إلى 4:00",
    sub: "عملي برمجة",
    place: "معامل من 6 - 13",
  },
  {
    section: 15,
    day: "wednesday",
    time: "من 8:30 إلى 10:00",
    sub: "تمارين رياضيات 2",
    place: "قاعة 1",
  },
  {
    section: 16,
    day: "wednesday",
    time: "من 8:30 إلى 10:00",
    sub: "تمارين رياضيات 2",
    place: "قاعة 1",
  },
  {
    section: 17,
    day: "wednesday",
    time: "من 8:30 إلى 10:00",
    sub: "تمارين رياضيات 2",
    place: "قاعة 1",
  },
  {
    section: 18,
    day: "wednesday",
    time: "من 8:30 إلى 10:00",
    sub: "تمارين رياضيات 2",
    place: "قاعة 2",
  },
  {
    section: 19,
    day: "wednesday",
    time: "من 8:30 إلى 10:00",
    sub: "تمارين رياضيات 2",
    place: "قاعة 2",
  },
  {
    section: 20,
    day: "wednesday",
    time: "من 8:30 إلى 10:00",
    sub: "تمارين رياضيات 2",
    place: "قاعة 2",
  },
  {
    section: 21,
    day: "wednesday",
    time: "من 8:30 إلى 10:00",
    sub: "تمارين رياضيات 2",
    place: "قاعة 3",
  },
  {
    section: 22,
    day: "wednesday",
    time: "من 8:30 إلى 10:00",
    sub: "تمارين رياضيات 2",
    place: "قاعة 3",
  },
  {
    section: 23,
    day: "wednesday",
    time: "من 10:00 إلى 11:30",
    sub: "تمارين رياضيات 2",
    place: "قاعة 1",
  },
  {
    section: 24,
    day: "wednesday",
    time: "من 10:00 إلى 11:30",
    sub: "تمارين رياضيات 2",
    place: "قاعة 1",
  },
  {
    section: 25,
    day: "wednesday",
    time: "من 10:00 إلى 11:30",
    sub: "تمارين رياضيات 2",
    place: "قاعة 1",
  },
  {
    section: 26,
    day: "wednesday",
    time: "من 10:00 إلى 11:30",
    sub: "تمارين رياضيات 2",
    place: "قاعة 2",
  },
  {
    section: 27,
    day: "wednesday",
    time: "من 10:00 إلى 11:30",
    sub: "تمارين رياضيات 2",
    place: "قاعة 2",
  },
  {
    section: 28,
    day: "wednesday",
    time: "من 10:00 إلى 11:30",
    sub: "تمارين رياضيات 2",
    place: "قاعة 2",
  },
  {
    section: 1,
    day: "wednesday",
    time: "من 10:00 إلى 11:30",
    sub: "تمارين رياضيات 2",
    place: "قاعة 3",
  },
  {
    section: 2,
    day: "wednesday",
    time: "من 10:00 إلى 11:30",
    sub: "تمارين رياضيات 2",
    place: "قاعة 3",
  },
  {
    section: 3,
    day: "wednesday",
    time: "من 11:30 إلى 1:00",
    sub: "تمارين رياضيات 2",
    place: "قاعة 1",
  },
  {
    section: 4,
    day: "wednesday",
    time: "من 11:30 إلى 1:00",
    sub: "تمارين رياضيات 2",
    place: "قاعة 1",
  },
  {
    section: 5,
    day: "wednesday",
    time: "من 11:30 إلى 1:00",
    sub: "تمارين رياضيات 2",
    place: "قاعة 1",
  },
  {
    section: 6,
    day: "wednesday",
    time: "من 11:30 إلى 1:00",
    sub: "تمارين رياضيات 2",
    place: "قاعة 2",
  },
  {
    section: 7,
    day: "wednesday",
    time: "من 11:30 إلى 1:00",
    sub: "تمارين رياضيات 2",
    place: "قاعة 2",
  },
  {
    section: 8,
    day: "wednesday",
    time: "من 11:30 إلى 1:00",
    sub: "تمارين رياضيات 2",
    place: "قاعة 2",
  },
  {
    section: 9,
    day: "wednesday",
    time: "من 11:30 إلى 1:00",
    sub: "تمارين رياضيات 2",
    place: "قاعة 3",
  },
  {
    section: 10,
    day: "wednesday",
    time: "من 11:30 إلى 1:00",
    sub: "تمارين رياضيات 2",
    place: "قاعة 3",
  },
  {
    section: 11,
    day: "wednesday",
    time: "من 1:00 إلى 2:30",
    sub: "تمارين رياضيات 2",
    place: "قاعة 1",
  },
  {
    section: 12,
    day: "wednesday",
    time: "من 1:00 إلى 2:30",
    sub: "تمارين رياضيات 2",
    place: "قاعة 1",
  },
  {
    section: 13,
    day: "wednesday",
    time: "من 1:00 إلى 2:30",
    sub: "تمارين رياضيات 2",
    place: "قاعة 2",
  },
  {
    section: 14,
    day: "wednesday",
    time: "من 1:00 إلى 2:30",
    sub: "تمارين رياضيات 2",
    place: "قاعة 2",
  },
  {
    section: 19,
    day: "thursday",
    time: "من 9:30 إلى 10:30",
    sub: "عملي تصميم منطقي",
    place: "كلية هندسة قسم مدني الدور الثاني علوى فصل 304",
  },
  {
    section: 20,
    day: "thursday",
    time: "من 9:30 إلى 10:30",
    sub: "عملي تصميم منطقي",
    place: "كلية هندسة قسم مدني الدور الثاني علوى فصل 304",
  },
  {
    section: 25,
    day: "thursday",
    time: "من 10:30 إلى 11:30",
    sub: "عملي تصميم منطقي",
    place: "كلية هندسة قسم مدني الدور الثاني علوى فصل 304",
  },
  {
    section: 26,
    day: "thursday",
    time: "من 10:30 إلى 11:30",
    sub: "عملي تصميم منطقي",
    place: "كلية هندسة قسم مدني الدور الثاني علوى فصل 304",
  },
  // {
  //   section: 31,
  //   day: "thursday",
  //   time: "من 11:30 إلى 12:30",
  //   sub: "عملي تصميم منطقي",
  //   place: "كلية هندسة قسم مدني الدور الثاني علوى فصل ",
  // },
  // {
  //   section: 32,
  //   day: "thursday",
  //   time: "من 11:30 إلى 12:30",
  //   sub: "عملي تصميم منطقي",
  //   place: "كلية هندسة قسم مدني الدور الثاني علوى فصل ",
  // },
  {
    section: 21,
    day: "thursday",
    time: "من 9:30 إلى 10:30",
    sub: "عملي تصميم منطقي",
    place: "كلية هندسة قسم مدني الدور الثاني علوى فصل 305",
  },
  {
    section: 22,
    day: "thursday",
    time: "من 9:30 إلى 10:30",
    sub: "عملي تصميم منطقي",
    place: "كلية هندسة قسم مدني الدور الثاني علوى فصل 305",
  },
  {
    section: 27,
    day: "thursday",
    time: "من 10:30 إلى 11:30",
    sub: "عملي تصميم منطقي",
    place: "كلية هندسة قسم مدني الدور الثاني علوى فصل 305",
  },
  {
    section: 28,
    day: "thursday",
    time: "من 10:30 إلى 11:30",
    sub: "عملي تصميم منطقي",
    place: "كلية هندسة قسم مدني الدور الثاني علوى فصل 305",
  },
  // {
  //   section: 33,
  //   day: "thursday",
  //   time: "من 10:30 إلى 12:00",
  //   sub: "عملي تصميم منطقي",
  //   place: "كلية هندسة قسم مدني الدور الثاني علوى فصل ",
  // },
  // {
  //   section: 34,
  //   day: "thursday",
  //   time: "من 10:30 إلى 12:00",
  //   sub: "عملي تصميم منطقي",
  //   place: "كلية هندسة قسم مدني الدور الثاني علوى فصل ",
  // },
  {
    section: 23,
    day: "thursday",
    time: "من 9:30 إلى 10:30",
    sub: "عملي تصميم منطقي",
    place: "كلية هندسة قسم مدني الدور الثاني علوى فصل 307",
  },
  {
    section: 24,
    day: "thursday",
    time: "من 9:30 إلى 10:30",
    sub: "عملي تصميم منطقي",
    place: "كلية هندسة قسم مدني الدور الثاني علوى فصل 307",
  },
  // {
  //   section: 29,
  //   day: "thursday",
  //   time: "من 12:00 إلى 1:30",
  //   sub: "عملي تصميم منطقي",
  //   place: "كلية هندسة قسم مدني الدور الثاني علوى فصل ",
  // },
  // {
  //   section: 30,
  //   day: "thursday",
  //   time: "من 12:00 إلى 1:30",
  //   sub: "عملي تصميم منطقي",
  //   place: "كلية هندسة قسم مدني الدور الثاني علوى فصل ",
  // },
  // {
  //   section: 35,
  //   day: "thursday",
  //   time: "من 12:00 إلى 1:30",
  //   sub: "عملي تصميم منطقي",
  //   place: "كلية هندسة قسم مدني الدور الثاني علوى فصل ",
  // },
  // {
  //   section: 36,
  //   day: "thursday",
  //   time: "من 12:00 إلى 1:30",
  //   sub: "عملي تصميم منطقي",
  //   place: "كلية هندسة قسم مدني الدور الثاني علوى فصل ",
  // },
  {
    section: 1,
    day: "thursday",
    time: "من 8:00 إلى 10:00",
    sub: "فيزياء",
    place: "الجامعة القديمة",
  },
  {
    section: 2,
    day: "thursday",
    time: "من 8:00 إلى 10:00",
    sub: "فيزياء",
    place: "الجامعة القديمة",
  },
  {
    section: 3,
    day: "thursday",
    time: "من 8:00 إلى 10:00",
    sub: "فيزياء",
    place: "الجامعة القديمة",
  },
  {
    section: 4,
    day: "thursday",
    time: "من 10:00 إلى 12:00",
    sub: "فيزياء",
    place: "الجامعة القديمة",
  },
  {
    section: 5,
    day: "thursday",
    time: "من 10:00 إلى 12:00",
    sub: "فيزياء",
    place: "الجامعة القديمة",
  },
  {
    section: 6,
    day: "thursday",
    time: "من 10:00 إلى 12:00",
    sub: "فيزياء",
    place: "الجامعة القديمة",
  },
  {
    section: 7,
    day: "thursday",
    time: "من 12:00 إلى 2:00",
    sub: "فيزياء",
    place: "الجامعة القديمة",
  },
  {
    section: 8,
    day: "thursday",
    time: "من 12:00 إلى 2:00",
    sub: "فيزياء",
    place: "الجامعة القديمة",
  },
  {
    section: 9,
    day: "thursday",
    time: "من 12:00 إلى 2:00",
    sub: "فيزياء",
    place: "الجامعة القديمة",
  },
  {
    section: 10,
    day: "thursday",
    time: "من 2:00 إلى 4:00",
    sub: "فيزياء",
    place: "الجامعة القديمة",
  },
  {
    section: 11,
    day: "thursday",
    time: "من 2:00 إلى 4:00",
    sub: "فيزياء",
    place: "الجامعة القديمة",
  },
  {
    section: 12,
    day: "thursday",
    time: "من 2:00 إلى 4:00",
    sub: "فيزياء",
    place: "الجامعة القديمة",
  },
  {
    section: 13,
    day: "thursday",
    time: "من 4:00 إلى 6:00",
    sub: "فيزياء",
    place: "الجامعة القديمة",
  },
  {
    section: 14,
    day: "thursday",
    time: "من 4:00 إلى 6:00",
    sub: "فيزياء",
    place: "الجامعة القديمة",
  },
  {
    section: 15,
    day: "thursday",
    time: "من 4:00 إلى 6:00",
    sub: "فيزياء",
    place: "الجامعة القديمة",
  },
  {
    section: 16,
    day: "thursday",
    time: "من 6:00 إلى 8:00",
    sub: "فيزياء",
    place: "الجامعة القديمة",
  },
  {
    section: 17,
    day: "thursday",
    time: "من 6:00 إلى 8:00",
    sub: "فيزياء",
    place: "الجامعة القديمة",
  },
  {
    section: 18,
    day: "thursday",
    time: "من 6:00 إلى 8:00",
    sub: "فيزياء",
    place: "الجامعة القديمة",
  },
];
