let data = [
  ///////////////////////////////////////////////////////////////////////////// saturday (السبت)

  {
    section: 24,
    day: "saturday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي برمجة هيكلية",
    place: "معمل 7",
  },
  {
    section: 25,
    day: "saturday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي برمجة هيكلية",
    place: "معمل 8",
  },
  {
    section: 27,
    day: "saturday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي هياكل بيانات",
    place: "معمل 11",
  },
  {
    section: 26,
    day: "saturday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي برمجة هيكلية",
    place: "معمل 7",
  },
  {
    section: 27,
    day: "saturday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي برمجة هيكلية",
    place: "معمل 8",
  },
  {
    section: 20,
    day: "saturday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي هياكل بيانات",
    place: "معمل 11",
  },
  {
    section: "all",
    day: "saturday",
    time: "من 11:30 إلى 1:00",
    sub: "نظم قواعد البيانات",
    place: "مدرج 2",
  },
  {
    section: "all",
    day: "saturday",
    time: "من 1:00 إلى 2:30",
    sub: "البرمجة الهيكلية",
    place: "مدرج 1",
  },
  {
    section: 26,
    day: "saturday",
    time: "من 2:30 إلى 4:00",
    sub: "عملي قواعد بيانات",
    place: "معمل 8",
  },
  {
    section: 27,
    day: "saturday",
    time: "من 2:30 إلى 4:00",
    sub: "عملي قواعد بيانات",
    place: "معمل 9",
  },

  ///////////////////////////////////////////////////////////////////////////// sunday (الأحد)

  {
    section: "all",
    day: "sunday",
    time: "من 10:00 إلى 11:30",
    sub: "رياضيات 3",
    place: "مدرج 2",
  },
  {
    section: "all",
    day: "sunday",
    time: "من 1:00 إلى 2:30",
    sub: "هياكل البيانات",
    place: "مدرج 1",
  },

  ///////////////////////////////////////////////////////////////////////////// monday (الإثنين)

  {
    section: 1,
    day: "monday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي برمجة هيكلية",
    place: "معمل 6",
  },
  {
    section: 2,
    day: "monday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي برمجة هيكلية",
    place: "معمل 7",
  },
  {
    section: 11,
    day: "monday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي برمجة هيكلية",
    place: "معمل 8",
  },
  {
    section: 3,
    day: "monday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي قواعد بيانات",
    place: "معمل 9",
  },
  {
    section: 4,
    day: "monday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي قواعد بيانات",
    place: "معمل 10",
  },
  {
    section: 12,
    day: "monday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي قواعد بيانات",
    place: "معمل 11",
  },
  {
    section: 3,
    day: "monday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي برمجة هيكلية",
    place: "معمل 6",
  },
  {
    section: 4,
    day: "monday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي برمجة هيكلية",
    place: "معمل 7",
  },
  {
    section: 12,
    day: "monday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي برمجة هيكلية",
    place: "معمل 8",
  },
  {
    section: 1,
    day: "monday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي قواعد بيانات",
    place: "معمل 9",
  },
  {
    section: 2,
    day: "monday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي قواعد بيانات",
    place: "معمل 10",
  },
  {
    section: 11,
    day: "monday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي قواعد بيانات",
    place: "معمل 11",
  },
  {
    section: 5,
    day: "monday",
    time: "من 11:30 إلى 1:00",
    sub: "عملي برمجة هيكلية",
    place: "معمل 6",
  },
  {
    section: 6,
    day: "monday",
    time: "من 11:30 إلى 1:00",
    sub: "عملي برمجة هيكلية",
    place: "معمل 7",
  },
  {
    section: 13,
    day: "monday",
    time: "من 11:30 إلى 1:00",
    sub: "عملي برمجة هيكلية",
    place: "معمل 8",
  },
  {
    section: 9,
    day: "monday",
    time: "من 11:30 إلى 1:00",
    sub: "عملي قواعد بيانات",
    place: "معمل 9",
  },
  {
    section: 10,
    day: "monday",
    time: "من 11:30 إلى 1:00",
    sub: "عملي قواعد بيانات",
    place: "معمل 10",
  },
  {
    section: 15,
    day: "monday",
    time: "من 11:30 إلى 1:00",
    sub: "عملي قواعد بيانات",
    place: "معمل 11",
  },
  {
    section: 7,
    day: "monday",
    time: "من 1:00 إلى 2:30",
    sub: "عملي برمجة هيكلية",
    place: "معمل 6",
  },
  {
    section: 8,
    day: "monday",
    time: "من 1:00 إلى 2:30",
    sub: "عملي برمجة هيكلية",
    place: "معمل 7",
  },
  {
    section: 14,
    day: "monday",
    time: "من 1:00 إلى 2:30",
    sub: "عملي برمجة هيكلية",
    place: "معمل 8",
  },
  {
    section: 5,
    day: "monday",
    time: "من 1:00 إلى 2:30",
    sub: "عملي قواعد بيانات",
    place: "معمل 9",
  },
  {
    section: 6,
    day: "monday",
    time: "من 1:00 إلى 2:30",
    sub: "عملي قواعد بيانات",
    place: "معمل 10",
  },
  {
    section: 13,
    day: "monday",
    time: "من 1:00 إلى 2:30",
    sub: "عملي قواعد بيانات",
    place: "معمل 11",
  },
  {
    section: 9,
    day: "monday",
    time: "من 2:30 إلى 4:00",
    sub: "عملي برمجة هيكلية",
    place: "معمل 6",
  },
  {
    section: 10,
    day: "monday",
    time: "من 2:30 إلى 4:00",
    sub: "عملي برمجة هيكلية",
    place: "معمل 7",
  },
  {
    section: 15,
    day: "monday",
    time: "من 2:30 إلى 4:00",
    sub: "عملي برمجة هيكلية",
    place: "معمل 8",
  },
  {
    section: 7,
    day: "monday",
    time: "من 2:30 إلى 4:00",
    sub: "عملي قواعد بيانات",
    place: "معمل 9",
  },
  {
    section: 8,
    day: "monday",
    time: "من 2:30 إلى 4:00",
    sub: "عملي قواعد بيانات",
    place: "معمل 10",
  },
  {
    section: 14,
    day: "monday",
    time: "من 2:30 إلى 4:00",
    sub: "عملي قواعد بيانات",
    place: "معمل 11",
  },

  ///////////////////////////////////////////////////////////////////////////// tuseday (الثلاثاء)

  {
    section: "all",
    day: "tuseday",
    time: "من 8:30 إلى 10:00",
    sub: "تنظيم الملفات",
    place: "مدرج 1",
  },
  {
    section: 1,
    day: "tuseday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي رياضيات 3",
    place: "قاعة 2",
  },
  {
    section: 2,
    day: "tuseday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي رياضيات 3",
    place: "قاعة 2",
  },
  {
    section: 3,
    day: "tuseday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي رياضيات 3",
    place: "قاعة 2",
  },
  {
    section: 4,
    day: "tuseday",
    time: "من 11:30 إلى 1:00",
    sub: "عملي رياضيات 3",
    place: "قاعة 2",
  },
  {
    section: 5,
    day: "tuseday",
    time: "من 11:30 إلى 1:00",
    sub: "عملي رياضيات 3",
    place: "قاعة 2",
  },
  {
    section: 6,
    day: "tuseday",
    time: "من 11:30 إلى 1:00",
    sub: "عملي رياضيات 3",
    place: "قاعة 2",
  },
  {
    section: "all",
    day: "tuseday",
    time: "من 1:00 إلى 2:30",
    sub: "عمارة الحاسب",
    place: "مدرج 2",
  },
  {
    section: 18,
    day: "tuseday",
    time: "من 2:30 إلى 4:00",
    sub: "عملي رياضيات 3",
    place: "قاعة 2",
  },
  {
    section: 22,
    day: "tuseday",
    time: "من 2:30 إلى 4:00",
    sub: "عملي رياضيات 3",
    place: "قاعة 2",
  },
  {
    section: 23,
    day: "tuseday",
    time: "من 2:30 إلى 4:00",
    sub: "عملي رياضيات 3",
    place: "قاعة 2",
  },

  ///////////////////////////////////////////////////////////////////////////// wednesday (الأربعاء)

  {
    section: 1,
    day: "wednesday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي تنظيم ملفات",
    place: "معمل 6",
  },
  {
    section: 2,
    day: "wednesday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي تنظيم ملفات",
    place: "معمل 7",
  },
  {
    section: 3,
    day: "wednesday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي تنظيم ملفات",
    place: "معمل 8",
  },
  {
    section: 4,
    day: "wednesday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي تنظيم ملفات",
    place: "معمل 13",
  },
  {
    section: 5,
    day: "wednesday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي هياكل بيانات",
    place: "معمل 9",
  },
  {
    section: 6,
    day: "wednesday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي هياكل بيانات",
    place: "معمل 10",
  },
  {
    section: 7,
    day: "wednesday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي هياكل بيانات",
    place: "معمل 11",
  },
  {
    section: 5,
    day: "wednesday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي تنظيم ملفات",
    place: "معمل 6",
  },
  {
    section: 6,
    day: "wednesday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي تنظيم ملفات",
    place: "معمل 7",
  },
  {
    section: 7,
    day: "wednesday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي تنظيم ملفات",
    place: "معمل 8",
  },
  {
    section: 8,
    day: "wednesday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي تنظيم ملفات",
    place: "معمل 13",
  },
  {
    section: 1,
    day: "wednesday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي هياكل بيانات",
    place: "معمل 9",
  },
  {
    section: 2,
    day: "wednesday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي هياكل بيانات",
    place: "معمل 10",
  },
  {
    section: 3,
    day: "wednesday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي هياكل بيانات",
    place: "معمل 11",
  },
  {
    section: 9,
    day: "wednesday",
    time: "من 11:30 إلى 1:00",
    sub: "عملي تنظيم ملفات",
    place: "معمل 6",
  },
  {
    section: 10,
    day: "wednesday",
    time: "من 11:30 إلى 1:00",
    sub: "عملي تنظيم ملفات",
    place: "معمل 7",
  },
  {
    section: 11,
    day: "wednesday",
    time: "من 11:30 إلى 1:00",
    sub: "عملي تنظيم ملفات",
    place: "معمل 8",
  },
  {
    section: 12,
    day: "wednesday",
    time: "من 11:30 إلى 1:00",
    sub: "عملي تنظيم ملفات",
    place: "معمل 13",
  },
  {
    section: 4,
    day: "wednesday",
    time: "من 11:30 إلى 1:00",
    sub: "عملي هياكل بيانات",
    place: "معمل 9",
  },
  {
    section: 8,
    day: "wednesday",
    time: "من 11:30 إلى 1:00",
    sub: "عملي هياكل بيانات",
    place: "معمل 10",
  },
  {
    section: 13,
    day: "wednesday",
    time: "من 11:30 إلى 1:00",
    sub: "عملي هياكل بيانات",
    place: "معمل 11",
  },
  {
    section: 13,
    day: "wednesday",
    time: "من 1:00 إلى 2:30",
    sub: "عملي تنظيم ملفات",
    place: "معمل 6",
  },
  {
    section: 14,
    day: "wednesday",
    time: "من 1:00 إلى 2:30",
    sub: "عملي تنظيم ملفات",
    place: "معمل 7",
  },
  {
    section: 15,
    day: "wednesday",
    time: "من 1:00 إلى 2:30",
    sub: "عملي تنظيم ملفات",
    place: "معمل 8",
  },
  {
    section: 16,
    day: "wednesday",
    time: "من 1:00 إلى 2:30",
    sub: "عملي تنظيم ملفات",
    place: "معمل 13",
  },
  {
    section: 9,
    day: "wednesday",
    time: "من 1:00 إلى 2:30",
    sub: "عملي هياكل بيانات",
    place: "معمل 9",
  },
  {
    section: 10,
    day: "wednesday",
    time: "من 1:00 إلى 2:30",
    sub: "عملي هياكل بيانات",
    place: "معمل 10",
  },
  {
    section: 17,
    day: "wednesday",
    time: "من 1:00 إلى 2:30",
    sub: "عملي هياكل بيانات",
    place: "معمل 11",
  },
  {
    section: 17,
    day: "wednesday",
    time: "من 2:30 إلى 4:00",
    sub: "عملي تنظيم ملفات",
    place: "معمل 6",
  },
  {
    section: 19,
    day: "wednesday",
    time: "من 2:30 إلى 4:00",
    sub: "عملي تنظيم ملفات",
    place: "معمل 7",
  },
  {
    section: 26,
    day: "wednesday",
    time: "من 2:30 إلى 4:00",
    sub: "عملي تنظيم ملفات",
    place: "معمل 8",
  },
  {
    section: 27,
    day: "wednesday",
    time: "من 2:30 إلى 4:00",
    sub: "عملي تنظيم ملفات",
    place: "معمل 13",
  },
  {
    section: 11,
    day: "wednesday",
    time: "من 2:30 إلى 4:00",
    sub: "عملي هياكل بيانات",
    place: "معمل 9",
  },
  {
    section: 14,
    day: "wednesday",
    time: "من 2:30 إلى 4:00",
    sub: "عملي هياكل بيانات",
    place: "معمل 10",
  },
  {
    section: 26,
    day: "wednesday",
    time: "من 2:30 إلى 4:00",
    sub: "عملي هياكل بيانات",
    place: "معمل 11",
  },

  ///////////////////////////////////////////////////////////////////////////// thursday (الخميس)

  {
    section: 16,
    day: "thursday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي برمجة هيكلية",
    place: "معمل 6",
  },
  {
    section: 17,
    day: "thursday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي برمجة هيكلية",
    place: "معمل 7",
  },
  {
    section: 18,
    day: "thursday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي قواعد بيانات",
    place: "معمل 8",
  },
  {
    section: 19,
    day: "thursday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي قواعد بيانات",
    place: "معمل 9",
  },
  {
    section: 23,
    day: "thursday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي تنظيم ملفات",
    place: "معمل 10",
  },
  {
    section: 25,
    day: "thursday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي تنظيم ملفات",
    place: "معمل 12",
  },
  {
    section: 22,
    day: "thursday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي هياكل بيانات",
    place: "معمل 11",
  },
  {
    section: 24,
    day: "thursday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي هياكل بيانات",
    place: "معمل 13",
  },
  {
    section: 10,
    day: "thursday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي رياضيات 3",
    place: "قاعة 2",
  },
  {
    section: 11,
    day: "thursday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي رياضيات 3",
    place: "قاعة 2",
  },
  {
    section: 12,
    day: "thursday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي رياضيات 3",
    place: "قاعة 2",
  },
  {
    section: 14,
    day: "thursday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي رياضيات 3",
    place: "قاعة 1",
  },
  {
    section: 20,
    day: "thursday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي رياضيات 3",
    place: "قاعة 1",
  },
  {
    section: 21,
    day: "thursday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي رياضيات 3",
    place: "قاعة 1",
  },
  {
    section: 19,
    day: "thursday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي برمجة هيكلية",
    place: "معمل 6",
  },
  {
    section: 18,
    day: "thursday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي برمجة هيكلية",
    place: "معمل 7",
  },
  {
    section: 16,
    day: "thursday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي قواعد بيانات",
    place: "معمل 8",
  },
  {
    section: 17,
    day: "thursday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي قواعد بيانات",
    place: "معمل 9",
  },
  {
    section: 20,
    day: "thursday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي تنظيم ملفات",
    place: "معمل 10",
  },
  {
    section: 22,
    day: "thursday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي تنظيم ملفات",
    place: "معمل 12",
  },
  {
    section: 21,
    day: "thursday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي هياكل بيانات",
    place: "معمل 11",
  },
  {
    section: 23,
    day: "thursday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي هياكل بيانات",
    place: "معمل 13",
  },
  {
    section: 7,
    day: "thursday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي رياضيات 3",
    place: "قاعة 1",
  },
  {
    section: 8,
    day: "thursday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي رياضيات 3",
    place: "قاعة 1",
  },
  {
    section: 9,
    day: "thursday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي رياضيات 3",
    place: "قاعة 1",
  },
  {
    section: 13,
    day: "thursday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي رياضيات 3",
    place: "قاعة 2",
  },
  {
    section: 15,
    day: "thursday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي رياضيات 3",
    place: "قاعة 2",
  },
  {
    section: 24,
    day: "thursday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي رياضيات 3",
    place: "قاعة 2",
  },
  {
    section: 20,
    day: "thursday",
    time: "من 11:30 إلى 1:00",
    sub: "عملي برمجة هيكلية",
    place: "معمل 6",
  },
  {
    section: 21,
    day: "thursday",
    time: "من 11:30 إلى 1:00",
    sub: "عملي برمجة هيكلية",
    place: "معمل 7",
  },
  {
    section: 22,
    day: "thursday",
    time: "من 11:30 إلى 1:00",
    sub: "عملي قواعد بيانات",
    place: "معمل 8",
  },
  {
    section: 23,
    day: "thursday",
    time: "من 11:30 إلى 1:00",
    sub: "عملي قواعد بيانات",
    place: "معمل 9",
  },
  {
    section: 18,
    day: "thursday",
    time: "من 11:30 إلى 1:00",
    sub: "عملي تنظيم ملفات",
    place: "معمل 10",
  },
  {
    section: 24,
    day: "thursday",
    time: "من 11:30 إلى 1:00",
    sub: "عملي تنظيم ملفات",
    place: "معمل 12",
  },
  {
    section: 12,
    day: "thursday",
    time: "من 11:30 إلى 1:00",
    sub: "عملي هياكل بيانات",
    place: "معمل 11",
  },
  {
    section: 15,
    day: "thursday",
    time: "من 11:30 إلى 1:00",
    sub: "عملي هياكل بيانات",
    place: "معمل 13",
  },
  {
    section: 16,
    day: "thursday",
    time: "من 11:30 إلى 1:00",
    sub: "عملي رياضيات 3",
    place: "قاعة 2",
  },
  {
    section: 17,
    day: "thursday",
    time: "من 11:30 إلى 1:00",
    sub: "عملي رياضيات 3",
    place: "قاعة 2",
  },
  {
    section: 19,
    day: "thursday",
    time: "من 11:30 إلى 1:00",
    sub: "عملي رياضيات 3",
    place: "قاعة 2",
  },
  {
    section: 25,
    day: "thursday",
    time: "من 11:30 إلى 1:00",
    sub: "عملي رياضيات 3",
    place: "قاعة 1",
  },
  {
    section: 26,
    day: "thursday",
    time: "من 11:30 إلى 1:00",
    sub: "عملي رياضيات 3",
    place: "قاعة 1",
  },
  {
    section: 27,
    day: "thursday",
    time: "من 11:30 إلى 1:00",
    sub: "عملي رياضيات 3",
    place: "قاعة 1",
  },
  {
    section: 22,
    day: "thursday",
    time: "من 1:00 إلى 2:30",
    sub: "عملي برمجة هيكلية",
    place: "معمل 6",
  },
  {
    section: 23,
    day: "thursday",
    time: "من 1:00 إلى 2:30",
    sub: "عملي برمجة هيكلية",
    place: "معمل 7",
  },
  {
    section: 20,
    day: "thursday",
    time: "من 1:00 إلى 2:30",
    sub: "عملي قواعد بيانات",
    place: "معمل 8",
  },
  {
    section: 24,
    day: "thursday",
    time: "من 1:00 إلى 2:30",
    sub: "عملي قواعد بيانات",
    place: "معمل 9",
  },
  {
    section: 21,
    day: "thursday",
    time: "من 1:00 إلى 2:30",
    sub: "عملي تنظيم ملفات",
    place: "معمل 10",
  },
  {
    section: 16,
    day: "thursday",
    time: "من 1:00 إلى 2:30",
    sub: "عملي هياكل بيانات",
    place: "معمل 11",
  },
  {
    section: 25,
    day: "thursday",
    time: "من 1:00 إلى 2:30",
    sub: "عملي هياكل بيانات",
    place: "معمل 13",
  },
  {
    section: 21,
    day: "thursday",
    time: "من 2:30 إلى 4:00",
    sub: "عملي قواعد بيانات",
    place: "معمل 8",
  },
  {
    section: 25,
    day: "thursday",
    time: "من 2:30 إلى 4:00",
    sub: "عملي قواعد بيانات",
    place: "معمل 9",
  },
  {
    section: 18,
    day: "thursday",
    time: "من 2:30 إلى 4:00",
    sub: "عملي هياكل بيانات",
    place: "معمل 11",
  },
  {
    section: 19,
    day: "thursday",
    time: "من 2:30 إلى 4:00",
    sub: "عملي هياكل بيانات",
    place: "معمل 13",
  },
  {
    section: 7,
    day: "thursday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي عمارة الحاسب",
    place: "هندسة",
  },
  {
    section: 8,
    day: "thursday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي عمارة الحاسب",
    place: "هندسة",
  },
  {
    section: 9,
    day: "thursday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي عمارة الحاسب",
    place: "هندسة",
  },
  {
    section: 10,
    day: "thursday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي عمارة الحاسب",
    place: "هندسة",
  },
  {
    section: 11,
    day: "thursday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي عمارة الحاسب",
    place: "هندسة",
  },
  {
    section: 12,
    day: "thursday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي عمارة الحاسب",
    place: "هندسة",
  },
  {
    section: 13,
    day: "thursday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي عمارة الحاسب",
    place: "هندسة",
  },
  {
    section: 14,
    day: "thursday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي عمارة الحاسب",
    place: "هندسة",
  },
  {
    section: 15,
    day: "thursday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي عمارة الحاسب",
    place: "هندسة",
  },
  {
    section: 16,
    day: "thursday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي عمارة الحاسب",
    place: "هندسة",
  },
  {
    section: 17,
    day: "thursday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي عمارة الحاسب",
    place: "هندسة",
  },
  {
    section: 18,
    day: "thursday",
    time: "من 11:30 إلى 1:00",
    sub: "عملي عمارة الحاسب",
    place: "هندسة",
  },
  {
    section: 19,
    day: "thursday",
    time: "من 11:30 إلى 1:00",
    sub: "عملي عمارة الحاسب",
    place: "هندسة",
  },
  {
    section: 20,
    day: "thursday",
    time: "من 11:30 إلى 1:00",
    sub: "عملي عمارة الحاسب",
    place: "هندسة",
  },
  {
    section: 21,
    day: "thursday",
    time: "من 11:30 إلى 1:00",
    sub: "عملي عمارة الحاسب",
    place: "هندسة",
  },
  {
    section: 22,
    day: "thursday",
    time: "من 11:30 إلى 1:00",
    sub: "عملي عمارة الحاسب",
    place: "هندسة",
  },
  {
    section: 23,
    day: "thursday",
    time: "من 1:00 إلى 2:30",
    sub: "عملي عمارة الحاسب",
    place: "هندسة",
  },
  {
    section: 24,
    day: "thursday",
    time: "من 1:00 إلى 2:30",
    sub: "عملي عمارة الحاسب",
    place: "هندسة",
  },
  {
    section: 25,
    day: "thursday",
    time: "من 1:00 إلى 2:30",
    sub: "عملي عمارة الحاسب",
    place: "هندسة",
  },
  {
    section: 26,
    day: "thursday",
    time: "من 1:00 إلى 2:30",
    sub: "عملي عمارة الحاسب",
    place: "هندسة",
  },
  {
    section: 27,
    day: "thursday",
    time: "من 1:00 إلى 2:30",
    sub: "عملي عمارة الحاسب",
    place: "هندسة",
  },
  {
    section: 1,
    day: "thursday",
    time: "من 2:30 إلى 4:00",
    sub: "عملي عمارة الحاسب",
    place: "هندسة",
  },
  {
    section: 2,
    day: "thursday",
    time: "من 2:30 إلى 4:00",
    sub: "عملي عمارة الحاسب",
    place: "هندسة",
  },
  {
    section: 3,
    day: "thursday",
    time: "من 2:30 إلى 4:00",
    sub: "عملي عمارة الحاسب",
    place: "هندسة",
  },
  {
    section: 4,
    day: "thursday",
    time: "من 2:30 إلى 4:00",
    sub: "عملي عمارة الحاسب",
    place: "هندسة",
  },
  {
    section: 5,
    day: "thursday",
    time: "من 2:30 إلى 4:00",
    sub: "عملي عمارة الحاسب",
    place: "هندسة",
  },
  {
    section: 6,
    day: "thursday",
    time: "من 2:30 إلى 4:00",
    sub: "عملي عمارة الحاسب",
    place: "هندسة",
  },
];
