let data = [
  // السبت
  {
    section: "all",
    day: "saturday",
    time: "من 11:30 إلى 1:00",
    sub: "رياضيات 3",
    place: "مدرج 2",
  },
  {
    section: "all",
    day: "saturday",
    time: "من 1:00 إلى 2:30",
    sub: "البرمجة الهيكلية",
    place: "مدرج 1",
  },

  // الأحد
  {
    section: 15,
    day: "sunday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي هياكل بيانات",
    place: "معمل 8",
  },
  {
    section: "all",
    day: "sunday",
    time: "من 10:00 إلى 11:30",
    sub: "نظم قواعد البيانات",
    place: "مدرج 2",
  },
  {
    section: 14,
    day: "sunday",
    time: "من 11:30 إلى 1:00",
    sub: "عملي هياكل بيانات",
    place: "معمل 11",
  },
  {
    section: "all",
    day: "sunday",
    time: "من 1:00 إلى 2:30",
    sub: "هياكل البيانات",
    place: "مدرج 1",
  },
  {
    section: 5,
    day: "sunday",
    time: "من 2:30 إلى 4:00",
    sub: "عملي برمجة هيكلية",
    place: "معمل 8",
  },

  // الإثنين
  {
    section: 1,
    day: "monday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي برمجة هيكلية",
    place: "معمل 6",
  },
  {
    section: 11,
    day: "monday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي برمجة هيكلية",
    place: "معمل 12",
  },
  {
    section: 3,
    day: "monday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي قواعد بيانات",
    place: "معمل 9",
  },
  {
    section: 4,
    day: "monday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي قواعد بيانات",
    place: "معمل 10",
  },
  {
    section: 12,
    day: "monday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي قواعد بيانات",
    place: "معمل 11",
  },
  {
    section: 3,
    day: "monday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي برمجة هيكلية",
    place: "معمل 6",
  },
  {
    section: 12,
    day: "monday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي برمجة هيكلية",
    place: "معمل 12",
  },
  {
    section: 1,
    day: "monday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي قواعد بيانات",
    place: "معمل 9",
  },
  {
    section: 2,
    day: "monday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي قواعد بيانات",
    place: "معمل 10",
  },
  {
    section: 14,
    day: "monday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي قواعد بيانات",
    place: "معمل 11",
  },
  {
    section: 2,
    day: "monday",
    time: "من 11:30 إلى 1:00",
    sub: "عملي برمجة هيكلية",
    place: "معمل 6",
  },
  {
    section: 6,
    day: "monday",
    time: "من 11:30 إلى 1:00",
    sub: "عملي برمجة هيكلية",
    place: "معمل 7",
  },
  {
    section: 13,
    day: "monday",
    time: "من 11:30 إلى 1:00",
    sub: "عملي برمجة هيكلية",
    place: "معمل 12",
  },
  {
    section: 10,
    day: "monday",
    time: "من 11:30 إلى 1:00",
    sub: "عملي قواعد بيانات",
    place: "معمل 9",
  },
  {
    section: 15,
    day: "monday",
    time: "من 11:30 إلى 1:00",
    sub: "عملي قواعد بيانات",
    place: "معمل 10",
  },
  {
    section: 13,
    day: "monday",
    time: "من 11:30 إلى 1:00",
    sub: "عملي هياكل بيانات",
    place: "معمل 11",
  },
  {
    section: 7,
    day: "monday",
    time: "من 1:00 إلى 2:30",
    sub: "عملي برمجة هيكلية",
    place: "معمل 6",
  },
  {
    section: 8,
    day: "monday",
    time: "من 1:00 إلى 2:30",
    sub: "عملي برمجة هيكلية",
    place: "معمل 7",
  },
  {
    section: 14,
    day: "monday",
    time: "من 1:00 إلى 2:30",
    sub: "عملي برمجة هيكلية",
    place: "معمل 12",
  },
  {
    section: 5,
    day: "monday",
    time: "من 1:00 إلى 2:30",
    sub: "عملي قواعد بيانات",
    place: "معمل 9",
  },
  {
    section: 6,
    day: "monday",
    time: "من 1:00 إلى 2:30",
    sub: "عملي قواعد بيانات",
    place: "معمل 10",
  },
  {
    section: 17,
    day: "monday",
    time: "من 1:00 إلى 2:30",
    sub: "عملي هياكل بيانات",
    place: "معمل 8",
  },
  {
    section: 7,
    day: "monday",
    time: "من 2:30 إلى 4:00",
    sub: "عملي قواعد بيانات",
    place: "معمل 9",
  },
  {
    section: 8,
    day: "monday",
    time: "من 2:30 إلى 4:00",
    sub: "عملي قواعد بيانات",
    place: "معمل 10",
  },
  {
    section: 9,
    day: "monday",
    time: "من 2:30 إلى 4:00",
    sub: "عملي برمجة هيكلية",
    place: "معمل 6",
  },
  {
    section: 10,
    day: "monday",
    time: "من 2:30 إلى 4:00",
    sub: "عملي برمجة هيكلية",
    place: "معمل 7",
  },
  {
    section: 15,
    day: "monday",
    time: "من 2:30 إلى 4:00",
    sub: "عملي برمجة هيكلية",
    place: "معمل 12",
  },

  // الثلاثاء
  {
    section: "all",
    day: "tuesday",
    time: "من 8:30 إلى 10:00",
    sub: "تنظيم الملفات",
    place: "مدرج 1",
  },
  {
    section: 1,
    day: "tuesday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي رياضيات 3",
    place: "قاعة 2",
  },
  {
    section: 2,
    day: "tuesday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي رياضيات 3",
    place: "قاعة 2",
  },
  {
    section: 3,
    day: "tuesday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي رياضيات 3",
    place: "قاعة 2",
  },
  {
    section: 5,
    day: "tuesday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي هياكل بيانات",
    place: "معمل 6",
  },
  {
    section: 16,
    day: "tuesday",
    time: "من 11:30 إلى 1:00",
    sub: "عملي رياضيات 3",
    place: "قاعة 2",
  },
  {
    section: 17,
    day: "tuesday",
    time: "من 11:30 إلى 1:00",
    sub: "عملي رياضيات 3",
    place: "قاعة 2",
  },
  {
    section: 18,
    day: "tuesday",
    time: "من 11:30 إلى 1:00",
    sub: "عملي قواعد بيانات",
    place: "معمل 8",
  },
  {
    section: "all",
    day: "tuesday",
    time: "من 1:00 إلى 2:30",
    sub: "عمارة الحاسب",
    place: "مدرج 2",
  },
  {
    section: 18,
    day: "tuesday",
    time: "من 2:30 إلى 4:00",
    sub: "عملي رياضيات 3",
    place: "قاعة 2",
  },
  {
    section: 19,
    day: "tuesday",
    time: "من 2:30 إلى 4:00",
    sub: "عملي رياضيات 3",
    place: "قاعة 2",
  },
  {
    section: 20,
    day: "tuesday",
    time: "من 2:30 إلى 4:00",
    sub: "عملي رياضيات 3",
    place: "قاعة 2",
  },

  // الأربعاء
  {
    section: 1,
    day: "wednesday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي تنظيم ملفات",
    place: "معمل 6",
  },
  {
    section: 2,
    day: "wednesday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي تنظيم ملفات",
    place: "معمل 7",
  },
  {
    section: 3,
    day: "wednesday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي تنظيم ملفات",
    place: "معمل 8",
  },
  {
    section: 6,
    day: "wednesday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي هياكل بيانات",
    place: "معمل 10",
  },
  {
    section: 7,
    day: "wednesday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي هياكل بيانات",
    place: "معمل 11",
  },
  {
    section: 5,
    day: "wednesday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي تنظيم ملفات",
    place: "معمل 12",
  },
  {
    section: 6,
    day: "wednesday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي تنظيم ملفات",
    place: "معمل 8",
  },
  {
    section: 7,
    day: "wednesday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي تنظيم ملفات",
    place: "معمل 7",
  },
  {
    section: 8,
    day: "wednesday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي تنظيم ملفات",
    place: "معمل 6",
  },
  {
    section: 2,
    day: "wednesday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي هياكل بيانات",
    place: "معمل 10",
  },
  {
    section: 3,
    day: "wednesday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي هياكل بيانات",
    place: "معمل 11",
  },
  {
    section: 9,
    day: "wednesday",
    time: "من 11:30 إلى 1:00",
    sub: "عملي تنظيم ملفات",
    place: "معمل 12",
  },
  {
    section: 10,
    day: "wednesday",
    time: "من 11:30 إلى 1:00",
    sub: "عملي تنظيم ملفات",
    place: "معمل 8",
  },
  {
    section: 11,
    day: "wednesday",
    time: "من 11:30 إلى 1:00",
    sub: "عملي تنظيم ملفات",
    place: "معمل 7",
  },
  {
    section: 12,
    day: "wednesday",
    time: "من 11:30 إلى 1:00",
    sub: "عملي تنظيم ملفات",
    place: "معمل 6",
  },
  {
    section: 1,
    day: "wednesday",
    time: "من 11:30 إلى 1:00",
    sub: "عملي هياكل بيانات",
    place: "معمل 13",
  },
  {
    section: 8,
    day: "wednesday",
    time: "من 11:30 إلى 1:00",
    sub: "عملي هياكل بيانات",
    place: "معمل 8",
  },
  {
    section: 13,
    day: "wednesday",
    time: "من 1:00 إلى 2:30",
    sub: "عملي تنظيم ملفات",
    place: "معمل 12",
  },
  {
    section: 14,
    day: "wednesday",
    time: "من 1:00 إلى 2:30",
    sub: "عملي تنظيم ملفات",
    place: "معمل 8",
  },
  {
    section: 15,
    day: "wednesday",
    time: "من 1:00 إلى 2:30",
    sub: "عملي تنظيم ملفات",
    place: "معمل 7",
  },
  {
    section: 16,
    day: "wednesday",
    time: "من 1:00 إلى 2:30",
    sub: "عملي تنظيم ملفات",
    place: "معمل 6",
  },
  {
    section: 10,
    day: "wednesday",
    time: "من 1:00 إلى 2:30",
    sub: "عملي هياكل بيانات",
    place: "معمل 18",
  },
  {
    section: 16,
    day: "wednesday",
    time: "من 1:00 إلى 2:30",
    sub: "عملي هياكل بيانات",
    place: "معمل 18",
  },
  {
    section: 4,
    day: "wednesday",
    time: "من 2:30 إلى 4:00",
    sub: "عملي تنظيم ملفات",
    place: "معمل 6",
  },
  {
    section: 17,
    day: "wednesday",
    time: "من 2:30 إلى 4:00",
    sub: "عملي تنظيم ملفات",
    place: "معمل 7",
  },
  {
    section: 18,
    day: "wednesday",
    time: "من 2:30 إلى 4:00",
    sub: "عملي تنظيم ملفات",
    place: "معمل 8",
  },
  {
    section: 11,
    day: "wednesday",
    time: "من 2:30 إلى 4:00",
    sub: "عملي هياكل بيانات",
    place: "معمل 11",
  },

  // الخميس
  {
    section: 8,
    day: "thursday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي عمارة الحاسب",
    place: "هندسة",
  },
  {
    section: 9,
    day: "thursday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي عمارة الحاسب",
    place: "هندسة",
  },
  {
    section: 10,
    day: "thursday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي عمارة الحاسب",
    place: "هندسة",
  },
  {
    section: 11,
    day: "thursday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي عمارة الحاسب",
    place: "هندسة",
  },
  {
    section: 12,
    day: "thursday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي عمارة الحاسب",
    place: "هندسة",
  },
  {
    section: 17,
    day: "thursday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي برمجة هيكلية",
    place: "معمل 7",
  },
  {
    section: 11,
    day: "thursday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي قواعد بيانات",
    place: "معمل 9",
  },
  {
    section: 12,
    day: "thursday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي هياكل بيانات",
    place: "معمل 11",
  },
  {
    section: 13,
    day: "thursday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي رياضيات 3",
    place: "قاعة 1",
  },
  {
    section: 14,
    day: "thursday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي رياضيات 3",
    place: "قاعة 1",
  },
  {
    section: 15,
    day: "thursday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي رياضيات 3",
    place: "قاعة 1",
  },
  {
    section: 4,
    day: "thursday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي رياضيات 3",
    place: "قاعة 2",
  },
  {
    section: 5,
    day: "thursday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي رياضيات 3",
    place: "قاعة 2",
  },
  {
    section: 6,
    day: "thursday",
    time: "من 8:30 إلى 10:00",
    sub: "عملي رياضيات 3",
    place: "قاعة 2",
  },
  {
    section: 13,
    day: "thursday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي عمارة الحاسب",
    place: "هندسة",
  },
  {
    section: 14,
    day: "thursday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي عمارة الحاسب",
    place: "هندسة",
  },
  {
    section: 15,
    day: "thursday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي عمارة الحاسب",
    place: "هندسة",
  },
  {
    section: 16,
    day: "thursday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي عمارة الحاسب",
    place: "هندسة",
  },
  {
    section: 17,
    day: "thursday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي عمارة الحاسب",
    place: "هندسة",
  },
  {
    section: 16,
    day: "thursday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي برمجة هيكلية",
    place: "معمل 6",
  },
  {
    section: 18,
    day: "thursday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي برمجة هيكلية",
    place: "معمل 7",
  },
  {
    section: 17,
    day: "thursday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي قواعد بيانات",
    place: "معمل 9",
  },
  {
    section: 4,
    day: "thursday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي هياكل بيانات",
    place: "معمل 11",
  },
  {
    section: 7,
    day: "thursday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي رياضيات 3",
    place: "قاعة 1",
  },
  {
    section: 8,
    day: "thursday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي رياضيات 3",
    place: "قاعة 1",
  },
  {
    section: 9,
    day: "thursday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي رياضيات 3",
    place: "قاعة 1",
  },
  {
    section: 10,
    day: "thursday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي رياضيات 3",
    place: "قاعة 2",
  },
  {
    section: 11,
    day: "thursday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي رياضيات 3",
    place: "قاعة 2",
  },
  {
    section: 12,
    day: "thursday",
    time: "من 10:00 إلى 11:30",
    sub: "عملي رياضيات 3",
    place: "قاعة 2",
  },
  {
    section: 18,
    day: "thursday",
    time: "من 11:30 إلى 1:00",
    sub: "عملي عمارة الحاسب",
    place: "هندسة",
  },
  {
    section: 19,
    day: "thursday",
    time: "من 11:30 إلى 1:00",
    sub: "عملي عمارة الحاسب",
    place: "هندسة",
  },
  {
    section: 20,
    day: "thursday",
    time: "من 11:30 إلى 1:00",
    sub: "عملي عمارة الحاسب",
    place: "هندسة",
  },
  {
    section: 4,
    day: "thursday",
    time: "من 11:30 إلى 1:00",
    sub: "عملي برمجة هيكلية",
    place: "معمل 7",
  },
  {
    section: 9,
    day: "thursday",
    time: "من 11:30 إلى 1:00",
    sub: "عملي هياكل بيانات",
    place: "معمل 11",
  },
  {
    section: 1,
    day: "thursday",
    time: "من 1:00 إلى 2:30",
    sub: "عملي عمارة الحاسب",
    place: "هندسة",
  },
  {
    section: 2,
    day: "thursday",
    time: "من 1:00 إلى 2:30",
    sub: "عملي عمارة الحاسب",
    place: "هندسة",
  },
  {
    section: 3,
    day: "thursday",
    time: "من 1:00 إلى 2:30",
    sub: "عملي عمارة الحاسب",
    place: "هندسة",
  },
  {
    section: 4,
    day: "thursday",
    time: "من 1:00 إلى 2:30",
    sub: "عملي عمارة الحاسب",
    place: "هندسة",
  },
  {
    section: 5,
    day: "thursday",
    time: "من 1:00 إلى 2:30",
    sub: "عملي عمارة الحاسب",
    place: "هندسة",
  },
  {
    section: 6,
    day: "thursday",
    time: "من 1:00 إلى 2:30",
    sub: "عملي عمارة الحاسب",
    place: "هندسة",
  },
  {
    section: 7,
    day: "thursday",
    time: "من 1:00 إلى 2:30",
    sub: "عملي عمارة الحاسب",
    place: "هندسة",
  },
  {
    section: 16,
    day: "thursday",
    time: "من 1:00 إلى 2:30",
    sub: "عملي قواعد بيانات",
    place: "معمل 9",
  },
  {
    section: 16,
    day: "thursday",
    time: "من 2:30 إلى 4:00",
    sub: "عملي قواعد بيانات",
    place: "معمل 10",
  },
];
